var new_lang = {
    lt1: 'richiedere il servizio di richiamata',
    lt2: 'effetti di «Tinedol»',
    lt3: 'efficacia',
    lt4: 'recensioni',
    lt5: 'un metodo facile per sconfiggere funghi, pruriti e lacerazioni!',
    lt6: 'cura il fungo dei piedi e delle unghie',
    lt7: 'elimina prurito e fastidio',
    lt8: 'elimina cattivo odore e sudorazione',
    lt9: 'ripara le lacerazioni sui talloni',
    lt10: 'SCONTO',
    lt11: '-50%',
    lt12: 'Serie limitata!<br>Affrettatevi!<br> solo <span class="product-how-much"><span class="lastpack">5</span> confezioni</span> <br>ad un prezzo speciale!',
    lt13: 'fino alla fine dell’offerat rimangono:',
    lt14: '00',
    lt15: 'ore',
    lt16: '25',
    lt17: 'minuti',
    lt18: '59',
    lt19: 'secondi',
    lt20: 'prezzo intero:',
    lt21: 'prezzo con lo sconto',
    lt22: 'ordinare',
    lt23: 'i vostri dati sono al sicuro',
    lt24: 'span class="title2-span1">pensate che il fungo non vi ha colpito?</span> se vi accorgete di avere almeno uno dei sintomi seguenti,<br> iniziate immediatamente la cura<',
    lt25: 'cattivo odore',
    lt26: 'lacerazioni e spaccature',
    lt27: 'unghie storte',
    lt28: 'unghie ingiallite <br>o marroni',
    lt29: 'macchie e punti bianche <br>sulle unghie',
    lt30: 'prurito e bruciore',
    lt31: 'vesciche',
    lt32: 'pelle rovinata',
    lt33: 'rigonfiamenti dell pelle <br>dei piedi',
    lt34: 'cosa succede se non si cura il fungo dei piedi',
    lt35: 'Secondo le statistiche un quinto degli italiani ha problemi di funghi.<br> Scarpe strett, cazini sintetici, saune, bagni turchi, piscine.<br> <span class="stage__span1">In estate poi si aggiungono spiagge m parchi ed ogni altro luogo dove si va scalzi.<br> tutto questo può comportare una terrificante malattia!</span> Fermi tutti!',
    lt36: 'Primo stadio:',
    lt37: '<i></i>fastidio',
    lt38: '<i></i>prurito',
    lt39: '<i></i>sudorazione',
    lt40: '<i></i>cattivo odore',
    lt41: '<i></i>scomodità',
    lt42: 'secondo stadio:',
    lt43: '<i></i>fungo delle unghie',
    lt44: '<i></i>spaccature profonde<',
    lt45: '<i></i>sudorazione e prurito aumentati',
    lt46: '<i></i>Tanfo',
    lt47: '<i></i>Unghie gialle e spesse',
    lt48: '<i></i>pelle “morta”',
    lt49: '<i></i>forte fastidio <br>quando si cammina',
    lt50: 'terzio stadio:',
    lt51: '<i></i>prurito e vesciche <br>tra le dita',
    lt52: '<i></i>lacerazioni e spaccature <br>profonde',
    lt53: '<i></i>dolore',
    lt54: '<i></i>pus',
    lt55: '<i></i>perdita delle unghie',
    lt56: '<span class="stage__main-block-span">se non si curano i piedi, possono subire una malattia tremenda!</span><br> pensate se queste fossero le vostre unghie! Volete queste piante del piede?<br>dite no!',
    lt57: 'come agisce <span class="title4-span1">la crema «Tinedol»?</span>',
    lt58: '<span class="work__span1">se utilizzata regolarmente «Tinedol» elimina subito diversi problemi.</span>i componenti contenuti nella crema eliminano velocemente',
    lt59: 'fungo',
    lt60: 'odore',
    lt61: 'sudore',
    lt62: 'spaccature',
    lt63: '<span class="consist__text--b">ckimbasolo</span> — blocca lo svilupparsi di lieviti e funghi. Elimina il prurito, uccide il fungo.',
    lt64: '<span class="consist__text--b">farnesolo</span> — “spegne” le ghiandole della sidurazione. Disinfeta, pulisce, e dona un buon odore a lungo. <span class="consist__text—b">IL PROPOLI </span> HA FORTI EFFETTI ANTIBATTERICI. <span class="consist__text—b">L’olio dell’albero da té </span> пpenetra in profondità nel substrato della pelle,curando in questo modo con efficacia le zone problematiche dell pelle, dona freschezza ed elimina gli odori molesti dalle zone che più soffrono dopo una giornata di lavoro . ',
    lt65: 'la crema idrata profondamente la pelle, le dona una forte difesa, elimina il fungo e cura le spaccature.',
    lt66: 'a differenza degli altri prodotti la crema «Tinedol» si può usare su tutta la superficie dei piedi. Si assorbe velocemente e non lascia segni sui vestiti. ',
    lt67: 'In edizione limitata assieme alla crema ne doniamo un altra per prendersi cura dei piedi secchi, idratante che dona benessere ai piedi stanchi.',
    lt68: 'un semplice metodo per sconfiggere <br>fungo prurito e spaccature!',
    lt69: 'Effetti dopo 30 giorni <span class="title6-span1">di utilizzo della crema</span> «Tinedol»',
    lt70: 'scompare il fungo <br>dei piedi e delle unghie',
    lt71: 'Inserite qui sotto i vostri dati',
    lt72: 'passano prurito<br>e vesciche',
    lt73: 'odore piacevole',
    lt74: 'i piedi non sudano',
    lt75: 'le spaccature <br>si riparano',
    lt76: 'benessere e movimenti <br>agevolati',
    lt77: 'piedi <br>belli e curati',
    lt78: 'come assumere <span class="title7-span1">la crema «Tinedol»?</span>',
    lt79: 'Prima dell’utilizzo pulite a fondo i piedi e asciugateli bene. Applicate uno strato sottile di crema sul piede. Ogni sera prima di dormire per 30 giorni.<br> Vi accorgerete che i talloni tornano di colore rosa e la pelle sembra nuova!',
    lt80: 'in che modo la crema «Tinedol» è meglio degli altri prodotti contro i funghi?',
    lt81: 'Ci sono due tipi di prodotti contro i funghi: i primi non aiutano, i secondi aiutano aiutano solo fino a quando vengono utilizzati. Le persone che soffrono di funghi, bisogna usare creme in continuazione.',
    lt82: '«Tinedol» cambia completamente la situazione. Gli studi clinici di massa dimostrano che questo prodotto è il più efficace contro i funghi di piedi e unghie. Già dopo il primo ciclo di cura il fungo passa e non torna. Questo effetto fortissimo è dovuto agli ingredienti naturali derivati dalla tradizione popolare.',
    lt83: 'Il parere dello specialista',
    lt84: 'Questo preparato ha dimostrato da tempo la sua efficacia. IL suo punto di forsa è l’ampio raggio d’azione. Anche se non avete tutti i sintomi è consigliabile usare «Tinedol» per una rapida profilassi preventiva. IL fungo delle unghie si sviluppa molto velocemente! Oggi avete un leggero prurito, e domani siete ricoverati in ospedale e dovete prendere antibiotici 5 volte al giorno. Non perdete tempo! Risolvete il problema ora. In più il fungo è infettivo. Se state male voi o un vostro caro a breve starà male tutta la famiglia!',
    lt85: '— Michele Passero<br>policlinico, Roma,  dottore dermatologo.',
    lt86: 'recensioni',
    lt87: 'Fino a «Tinedol» pensavo che i funghi potessero scomparire solo per poco e poi tornae... ho provato qualsiasi prodotto. Evidentemente spaivano solo i sintomi ma il fungo rimaneva. Poi un dottore mi ha consigliato «Tinedol». Sono sei mesi che non ho problemi. <br>grazie!',
    lt88: 'Marina, Roma',
    lt89: 'Talloni come quelli dei bambini! Vado di continuo in piscina. Quando ho saputo di avere il fungo non mi sono neanche troppo stupita, docce comuni, spoglaitoi comuni, il cloro non salva dai funghi. Che fare. Tutte le ragazze dello spogliatoglio sano che meglio di «Tinedol» non esiste alcun prodotto! Lo usiamo tutte e non abbiamo problemi di funghi!',
    lt90: 'Alessandra, Venezia',
    lt91: 'IL fungo si abitua alle medicine che si usano. A mio marito le gambe sudavano in maniera atroce,e il fungo quindi viveva bene. Abbiamo preso «Tinedol» per vie di due sue grandi qualità. Difesa da sudorazionne e funghi. 3 mesi lo ha spalmato, ora è passato tutto!',
    lt92: 'Valeria, Faenza',
    lt93: '',
    title: 'comprare «Tinedol»a poco. Prezzi, recensioni. Ordinate Tinedol ora!'
};

function Translater() {
    for (class_name in new_lang) {
        var elements = document.getElementsByClassName(class_name);
        if (elements.length) {
            for (key in elements) {
                elements[key].innerHTML = new_lang[class_name];
            }
        }
    }
};